urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from presentations.views import PresentationView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^p/(?P<slug>[-\w]+)/$',PresentationView.as_view(),name="presentation"),
    url(r'^admin/', include(admin.site.urls)),
)

presentations/models.py
from autoslug import AutoSlugField
from django.db import models

from django.utils.translation import ugettext as _

# Create your models here.

class Presentation(models.Model):
    name = models.CharField(max_length=250,verbose_name=_("Name"))
    slug = AutoSlugField(populate_from='name')
    creation_time = models.DateTimeField(auto_now_add=True,editable=False,verbose_name=_("Creation time"))
    modification_time = models.DateTimeField(auto_now=True,editable=False,verbose_name=_("Modification time"))

    class Meta:
        verbose_name = _("Presentation")
        verbose_name_plural = _("Presentations")
        ordering = ('modification_time','name')

    def __unicode__(self):
        return self.name

class Slide(models.Model):
    presentation = models.ForeignKey(Presentation,verbose_name=_("Presentation"))
    title = models.CharField(max_length=250,null=True,blank=True,unique=True,verbose_name=_("Title"))
    title_slug = AutoSlugField(populate_from='title',unique=True,verbose_name=_("Slug"),null=True,blank=True)
    css_class = models.CharField(max_length=250, null=True,blank=True)
    content = models.TextField(verbose_name=_("Content"))
    creation_time = models.DateTimeField(auto_now_add=True,editable=False,verbose_name=_("Creation time"))
    modification_time = models.DateTimeField(auto_now=True,editable=False,verbose_name=_("Modification time"))

    order = models.PositiveIntegerField(verbose_name=_("Ordering"))

    data_x = models.IntegerField(verbose_name=_("X coordinate"),help_text=_("X coordinate of the center of slide"), default=0)
    data_y = models.IntegerField(verbose_name=_("Y coordinate"),help_text=_("Y coordinate of the center of slide"), default=0)
    data_z = models.IntegerField(verbose_name=_("Z coordinate"),help_text=_("Z coordinate of the center of slide"), default=0)

    scale = models.IntegerField(verbose_name=_("Scale"),default=1)

    rotate_x = models.IntegerField(verbose_name=_("Rotation over X axis"),default=0)
    rotate_y = models.IntegerField(verbose_name=_("Rotation over Y axis"),default=0)
    rotate_z = models.IntegerField(verbose_name=_("Rotation over Z axis"),default=0)

    class Meta:
        verbose_name = _("Slide")
        verbose_name_plural = _("Slides")
        unique_together = ('order','presentation')
        ordering = ('order',)



    def save(self, **kwargs):
        self.presentation.save()
        return super(Slide,self).save(**kwargs)

    def __unicode__(self):
        return self.title or self.presentation

presentations/forms.py
# -*- coding: utf-8 -*-
from django import forms
from presentations.models import Slide

class SlideForm(forms.ModelForm):
    class Meta:
        model = Slide

    def clean_title(self):
        return self.cleaned_data['title'] or None

    def clean_title_slug(self):
        return self.cleaned_data['title_slug'] or None

presentations/views.py
# Create your views here.
from django.views.generic.detail import DetailView
from presentations.models import Presentation

class PresentationView(DetailView):
    model = Presentation
    template_name = 'presentations/presentation.html'
    context_object_name = 'presentation'

presentations/templates/presentations/presentation.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>{{ presentation.name }}</title>
    <meta name="viewport" content="width=1024" />
<link rel="stylesheet" href="{{ STATIC_URL }}css/impress-demo.css" />
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.min.js"></script>

<script type="text/javascript" src="{{ STATIC_URL }}js/highlight.min.js"></script>
<link rel="stylesheet" href="{{ STATIC_URL }}css/default.css">
    <script type="text/javascript">
        hljs.tabReplace = '    ';
        hljs.initHighlightingOnLoad();
    </script>

</head>
<body>
<div id="impress" class="impress-not-supported">
    {% for slide in presentation.slide_set.all %}
        {% include "presentations/slide.html" %}
    {% endfor %}
</div>
<script src="{{ STATIC_URL }}js/impress.js" script type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function(){
        impress().init();
    });
</script>
</body>
</html>

presentations/templates/presentations/slide.html
<div{% if slide.title_slug %}
    id="{{ slide.title_slug }}"
{% endif %} data-x="{{ slide.data_x }}" data-y="{{ slide.data_y }}" data-z="{{ slide.data_z }}" data-scale="{{ slide.scale }}" data-rotate-x="{{ slide.rotate_x }}" data-rotate-y="{{ slide.rotate_y }}" data-rotate-z="{{ slide.rotate_z }}" class="step {{ slide.css_class }}">
    {{ slide.content|safe }}
</div>